import type {
  Alert,
  AlertHistoryResponse,
  DashboardData,
  Device,
  DeviceDetail,
  DeviceHealthCheck,
  DeviceHealthHistory,
  DeviceStatus,
  DeviceType,
  CheckLog,
  GoogleSsoConfig,
  ImportLog,
  Site,
  SiteUptimeReport,
  Token,
  UptimeReport,
  User,
} from '@/types'

const now = new Date()
const iso = (hoursAgo = 0) => new Date(now.getTime() - hoursAgo * 60 * 60 * 1000).toISOString()

const user: User = {
  id: 'demo-user',
  email: 'admin@camwatch.com',
  full_name: 'Administrator',
  is_active: true,
  is_superuser: true,
  role: 'ADMIN',
  created_at: iso(240),
}

export const demoSites: Site[] = [
  {
    id: 'site-bellahalli',
    name: 'Bellahalli, Jakkur Post, Bangalore',
    city: 'Bangalore',
    address: 'Bellahalli, Jakkur Post, Bangalore',
    contact_name: 'Ramesh Kumar',
    contact_phone: '9876543210',
    contact_email: 'bellahalli@example.com',
    regional_head_name: 'South Head',
    regional_manager_name: 'South Manager',
    is_active: true,
    created_at: iso(900),
    total_devices: 4,
    online_devices: 2,
    degraded_devices: 1,
    offline_devices: 1,
  },
  {
    id: 'site-dwarka',
    name: 'Radisson Blu, Dwarka',
    city: 'Delhi',
    address: 'Radisson Blu, Dwarka, Delhi',
    contact_name: 'Neha Sharma',
    contact_phone: '9876501234',
    contact_email: 'dwarka@example.com',
    regional_head_name: 'North Head',
    regional_manager_name: 'North Manager',
    is_active: true,
    created_at: iso(700),
    total_devices: 3,
    online_devices: 3,
    degraded_devices: 0,
    offline_devices: 0,
  },
  {
    id: 'site-kandivali',
    name: 'Kandivali, Mumbai OPS',
    city: 'Mumbai',
    address: 'Kandivali, Mumbai OPS',
    contact_name: 'Amit Mehta',
    contact_phone: '9876509876',
    contact_email: 'kandivali@example.com',
    regional_head_name: 'West Head',
    regional_manager_name: 'West Manager',
    is_active: true,
    created_at: iso(650),
    total_devices: 5,
    online_devices: 3,
    degraded_devices: 1,
    offline_devices: 1,
  },
]

export const demoDevices: Device[] = [
  {
    id: 'dev-nvr-bellahalli',
    name: 'Hikvision NVR',
    site_id: 'site-bellahalli',
    site_name: 'Bellahalli, Jakkur Post, Bangalore',
    device_type: 'nvr',
    ip_address: '106.51.37.18',
    port: 82,
    rtsp_port: 554,
    username: 'admin',
    rtsp_mode: 'auto',
    rtsp_stream_type: 'main',
    rtsp_url: 'rtsp://admin:******@106.51.37.18:554/Streaming/Channels/101',
    vendor: 'Hikvision',
    model: 'DS-7608NI-K2',
    serial_number: 'DS-7608NI-K2/123456789',
    firmware_version: 'V4.72.000 build 240101',
    area: 'Entrance',
    channel_count: 16,
    channels_used: 10,
    notes: 'Zone: South',
    is_active: true,
    status: 'degraded',
    ping_status: true,
    rtsp_status: false,
    latest_ping_latency_ms: 283,
    latest_ping_packet_loss_pct: 0,
    last_seen: iso(0.2),
    downtime_seconds: 6900,
    created_at: iso(1100),
  },
  {
    id: 'dev-cam-bellahalli-1',
    name: 'Gate Camera 01',
    site_id: 'site-bellahalli',
    site_name: 'Bellahalli, Jakkur Post, Bangalore',
    device_type: 'camera',
    ip_address: '106.51.37.19',
    port: 80,
    rtsp_port: 554,
    username: 'admin',
    rtsp_mode: 'auto',
    rtsp_stream_type: 'main',
    vendor: 'Hikvision',
    area: 'Gate',
    is_active: true,
    status: 'online',
    ping_status: true,
    rtsp_status: true,
    api_status: true,
    latest_ping_latency_ms: 96,
    latest_ping_packet_loss_pct: 0,
    last_seen: iso(0.1),
    downtime_seconds: 0,
    created_at: iso(950),
  },
  {
    id: 'dev-cam-bellahalli-2',
    name: 'Parking Camera 02',
    site_id: 'site-bellahalli',
    site_name: 'Bellahalli, Jakkur Post, Bangalore',
    device_type: 'camera',
    ip_address: '106.51.37.20',
    port: 80,
    rtsp_port: 554,
    username: 'admin',
    rtsp_mode: 'auto',
    rtsp_stream_type: 'main',
    vendor: 'Hikvision',
    area: 'Parking',
    is_active: true,
    status: 'offline',
    ping_status: false,
    rtsp_status: false,
    last_seen: iso(7),
    downtime_seconds: 25200,
    created_at: iso(950),
  },
  {
    id: 'dev-nvr-dwarka',
    name: 'UNV NVR',
    site_id: 'site-dwarka',
    site_name: 'Radisson Blu, Dwarka',
    device_type: 'nvr',
    ip_address: '103.62.94.139',
    port: 83,
    rtsp_port: 555,
    username: 'admin',
    rtsp_mode: 'auto',
    rtsp_stream_type: 'main',
    rtsp_url: 'rtsp://admin:******@103.62.94.139:555/unicast/c1/s0/live',
    vendor: 'UNV',
    model: 'NVR301-16',
    area: 'Lobby',
    channel_count: 16,
    channels_used: 15,
    is_active: true,
    status: 'online',
    ping_status: true,
    rtsp_status: true,
    api_status: true,
    latest_ping_latency_ms: 122,
    latest_ping_packet_loss_pct: 0,
    last_seen: iso(0.05),
    downtime_seconds: 0,
    created_at: iso(870),
  },
  {
    id: 'dev-nvr-kandivali',
    name: 'Hikvision',
    site_id: 'site-kandivali',
    site_name: 'Kandivali, Mumbai OPS',
    device_type: 'nvr',
    ip_address: '103.113.141.92',
    port: 82,
    rtsp_port: 554,
    username: 'admin',
    rtsp_mode: 'auto',
    rtsp_stream_type: 'main',
    rtsp_url: 'rtsp://admin:******@103.113.141.92:554/Streaming/Channels/101',
    vendor: 'Hikvision',
    channel_count: 16,
    channels_used: 13,
    notes: 'Zone: West',
    is_active: true,
    status: 'degraded',
    ping_status: true,
    rtsp_status: true,
    api_status: false,
    latest_ping_latency_ms: 54,
    latest_ping_packet_loss_pct: 0,
    last_seen: iso(0.4),
    downtime_seconds: 7140,
    created_at: iso(1000),
  },
]

export const demoAlerts: Alert[] = [
  {
    id: 'alert-rtsp-bellahalli',
    device_id: 'dev-nvr-bellahalli',
    site_id: 'site-bellahalli',
    device_type: 'nvr',
    alert_type: 'nvr_rtsp_failure',
    severity: 'critical',
    state: 'open',
    status: 'open',
    title: 'RTSP failure',
    message: 'RTSP authentication failed on primary stream.',
    occurrence_count: 7,
    created_at: iso(2.2),
    last_seen_at: iso(0.2),
    device_name: 'Hikvision NVR',
    site_name: 'Bellahalli, Jakkur Post, Bangalore',
  },
  {
    id: 'alert-cam-offline',
    device_id: 'dev-cam-bellahalli-2',
    site_id: 'site-bellahalli',
    device_type: 'camera',
    alert_type: 'camera_offline',
    severity: 'high',
    state: 'open',
    status: 'open',
    title: 'Camera offline',
    message: 'Ping and RTSP checks failed.',
    occurrence_count: 12,
    created_at: iso(7),
    last_seen_at: iso(0.5),
    device_name: 'Parking Camera 02',
    site_name: 'Bellahalli, Jakkur Post, Bangalore',
  },
  {
    id: 'alert-api-kandivali',
    device_id: 'dev-nvr-kandivali',
    site_id: 'site-kandivali',
    device_type: 'nvr',
    alert_type: 'api_failure',
    severity: 'medium',
    state: 'acknowledged',
    status: 'acknowledged',
    title: 'API failure',
    message: 'HTTP endpoint timed out, RTSP and ping are healthy.',
    occurrence_count: 3,
    created_at: iso(4),
    acknowledged_at: iso(3.5),
    last_seen_at: iso(0.4),
    device_name: 'Hikvision',
    site_name: 'Kandivali, Mumbai OPS',
  },
]

const checkLogs = (device: Device) => {
  const logs: CheckLog[] = [
    {
      id: `${device.id}-ping`,
      device_id: device.id,
      check_type: 'ping' as const,
      success: !!device.ping_status,
      latency_ms: device.latest_ping_latency_ms,
      packet_loss_pct: device.latest_ping_packet_loss_pct,
      error_message: device.ping_status ? undefined : 'Ping failed',
      checked_at: iso(0.1),
    },
    {
      id: `${device.id}-rtsp`,
      device_id: device.id,
      check_type: 'rtsp' as const,
      success: !!device.rtsp_status,
      latency_ms: device.rtsp_status ? 156 : undefined,
      error_message: device.rtsp_status ? undefined : 'Authentication failed',
      checked_at: iso(0.1),
    },
  ]

  if (device.device_type === 'nvr') {
    logs.push({
      id: `${device.id}-api`,
      device_id: device.id,
      check_type: 'api' as const,
      success: !!device.api_status,
      latency_ms: device.api_status ? 118 : undefined,
      error_message: device.api_status ? undefined : 'HTTP timeout',
      checked_at: iso(0.1),
    })
  }

  return logs
}

export const demoApi = {
  auth: {
    login: async (): Promise<Token> => ({ access_token: 'demo-token', token_type: 'bearer' }),
    googleConfig: async (): Promise<GoogleSsoConfig> => ({ enabled: false }),
    googleLogin: async (): Promise<Token> => ({ access_token: 'demo-token', token_type: 'bearer' }),
    me: async (): Promise<User> => user,
    register: async (): Promise<User> => user,
  },
  dashboard: {
    get: async (): Promise<DashboardData> => {
      const cameras = demoDevices.filter((device) => device.device_type === 'camera')
      const nvrs = demoDevices.filter((device) => device.device_type === 'nvr')
      return {
        stats: {
          total_cameras: cameras.length,
          online_cameras: cameras.filter((device) => device.status !== 'offline').length,
          degraded_cameras: cameras.filter((device) => device.status === 'degraded').length,
          offline_cameras: cameras.filter((device) => device.status === 'offline').length,
          standalone_cameras: 1,
          nvr_linked_cameras: 1,
          total_nvrs: nvrs.length,
          online_nvrs: nvrs.filter((device) => device.status !== 'offline').length,
          degraded_nvrs: nvrs.filter((device) => device.status === 'degraded').length,
          offline_nvrs: nvrs.filter((device) => device.status === 'offline').length,
          healthy_nvrs: nvrs.filter((device) => device.status === 'online').length,
          failed_nvrs: nvrs.filter((device) => device.status === 'offline').length,
          total_sites: demoSites.length,
          active_alerts: demoAlerts.filter((alert) => alert.state !== 'resolved').length,
          critical_alerts: demoAlerts.filter((alert) => alert.severity === 'critical').length,
        },
        site_statuses: demoSites.map((site) => ({
          site_id: site.id,
          site_name: site.name,
          total_devices: site.total_devices || 0,
          online_devices: site.online_devices || 0,
          degraded_devices: site.degraded_devices || 0,
          offline_devices: site.offline_devices || 0,
          uptime_percent: site.total_devices ? Math.round(((site.online_devices || 0) / site.total_devices) * 100) : 0,
        })),
        critical_alerts: demoAlerts.filter((alert) => alert.severity === 'critical'),
        offline_cameras: cameras.filter((device) => device.status === 'offline'),
        critical_nvrs: nvrs.filter((device) => device.status !== 'online'),
      }
    },
  },
  sites: {
    list: async (): Promise<Site[]> => demoSites,
    get: async (id: string): Promise<Site> => demoSites.find((site) => site.id === id) || demoSites[0],
    create: async (data: Partial<Site>): Promise<Site> => ({ ...demoSites[0], ...data, id: `demo-site-${Date.now()}` }),
    update: async (id: string, data: Partial<Site>): Promise<Site> => ({ ...(demoSites.find((site) => site.id === id) || demoSites[0]), ...data }),
    delete: async (): Promise<void> => undefined,
  },
  devices: {
    list: async (params?: { site_id?: string; device_type?: DeviceType; status?: DeviceStatus }): Promise<Device[]> =>
      demoDevices.filter((device) =>
        (!params?.site_id || device.site_id === params.site_id) &&
        (!params?.device_type || device.device_type === params.device_type) &&
        (!params?.status || device.status === params.status)
      ),
    get: async (id: string): Promise<DeviceDetail> => {
      const device = demoDevices.find((item) => item.id === id) || demoDevices[0]
      return {
        ...device,
        recent_checks: checkLogs(device),
        open_alerts: demoAlerts.filter((alert) => alert.device_id === device.id && alert.state !== 'resolved'),
      }
    },
    healthHistory: async (id: string): Promise<DeviceHealthHistory> => {
      const device = demoDevices.find((item) => item.id === id) || demoDevices[0]
      const statuses: Array<DeviceStatus | 'no_data'> = [
        'online', 'online', 'online', 'online', 'online', 'degraded', 'degraded', 'degraded',
        'offline', 'offline', 'online', 'online', 'online', 'online', 'online', 'online',
        'online', 'online', 'online', 'online', 'online', 'online', 'online', device.status,
      ]
      const timeline = statuses.map((status, index) => {
        const start = new Date(now.getTime() - (24 - index) * 60 * 60 * 1000)
        const end = new Date(start.getTime() + 60 * 60 * 1000)
        return {
          start_at: start.toISOString(),
          end_at: end.toISOString(),
          status,
          reason: status === 'online' ? 'All checks healthy' : status === 'degraded' ? 'RTSP failed, other checks healthy' : status === 'offline' ? 'Critical checks failed' : 'No samples',
          checks: [
            { label: 'Ping', status: status === 'offline' ? 'failed' as const : 'healthy' as const, detail: status === 'offline' ? 'Failed' : 'OK' },
            { label: 'RTSP', status: status === 'degraded' || status === 'offline' ? 'failed' as const : 'healthy' as const, detail: status === 'degraded' ? 'Authentication failed' : status === 'offline' ? 'Timeout' : 'OK' },
            ...(device.device_type === 'nvr'
              ? [{ label: 'API', status: status === 'offline' ? 'failed' as const : 'healthy' as const, detail: status === 'offline' ? 'Timeout' : '200 OK' }]
              : []),
          ],
        }
      })
      const currentChecks: DeviceHealthCheck[] = [
        { key: 'ping', label: 'Ping', status: device.ping_status ? 'healthy' as const : 'failed' as const, reason: device.ping_status ? 'Pass' : 'Ping failed', metrics: device.latest_ping_latency_ms ? `${device.latest_ping_latency_ms} ms` : null, observed_at: iso(0.1) },
        { key: 'rtsp', label: 'RTSP', status: device.rtsp_status ? 'healthy' as const : 'failed' as const, reason: device.rtsp_status ? 'Pass' : 'Authentication Failed', metrics: device.rtsp_status ? 'Stream OK' : null, observed_at: iso(0.1) },
        ...(device.device_type === 'nvr'
          ? [
              { key: 'api', label: 'API', status: device.api_status ? 'healthy' as const : 'failed' as const, reason: device.api_status ? 'Pass' : 'HTTP timeout', metrics: device.api_status ? '200 OK' : null, observed_at: iso(0.1) },
              { key: 'recording', label: 'Recording', status: 'no_data' as const, reason: 'No Data', metrics: 'No recent check data', observed_at: null },
            ]
          : []),
      ]
      return {
        device_id: device.id,
        current_status: device.status,
        last_seen: device.last_seen,
        latency_ms: device.latest_ping_latency_ms,
        uptime_24h_percent: device.status === 'online' ? 96.4 : 90.2,
        online_minutes: 1300,
        degraded_minutes: 115,
        offline_minutes: 25,
        no_data_minutes: 0,
        current_checks: currentChecks,
        timeline,
        events: [
          { timestamp: iso(0.2), severity: 'critical', title: 'RTSP Authentication Failed', reason: 'Stream authentication failed', status: 'degraded' },
          { timestamp: iso(0.2), severity: 'medium', title: 'Device Status changed to Degraded', reason: 'RTSP failed, other services healthy', status: 'degraded' },
          { timestamp: iso(1.1), severity: 'low', title: 'API Recovered', reason: 'API responding normally', status: 'online' },
          { timestamp: iso(3.5), severity: 'high', title: 'API Timeout', reason: 'HTTP request timeout', status: 'degraded' },
          { timestamp: iso(4.1), severity: 'low', title: 'Recovered', reason: 'Device checks returned to normal', status: 'online' },
        ],
      }
    },
    create: async (data: Partial<Device>): Promise<Device> => ({ ...demoDevices[0], ...data, id: `demo-device-${Date.now()}` }),
    update: async (id: string, data: Partial<Device>): Promise<Device> => ({ ...(demoDevices.find((device) => device.id === id) || demoDevices[0]), ...data }),
    delete: async (): Promise<void> => undefined,
    triggerCheck: async (): Promise<{ message: string }> => ({ message: 'Demo check queued' }),
    importCsv: async (file: File): Promise<ImportLog> => ({ id: 'demo-import', filename: file.name, total_rows: 12, success_rows: 12, failed_rows: 0, created_at: iso(0) }),
    importHistory: async (): Promise<ImportLog[]> => [{ id: 'demo-import', filename: 'demo.csv', total_rows: 12, success_rows: 12, failed_rows: 0, created_at: iso(2) }],
  },
  alerts: {
    list: async (): Promise<Alert[]> => demoAlerts,
    acknowledge: async (id: string): Promise<Alert> => ({ ...(demoAlerts.find((alert) => alert.id === id) || demoAlerts[0]), state: 'acknowledged', status: 'acknowledged' }),
    recover: async (id: string): Promise<Alert> => ({ ...(demoAlerts.find((alert) => alert.id === id) || demoAlerts[0]), state: 'recovered', status: 'recovered' }),
    resolve: async (id: string): Promise<Alert> => ({ ...(demoAlerts.find((alert) => alert.id === id) || demoAlerts[0]), state: 'resolved', status: 'resolved' }),
    summary: async (): Promise<{ open: number; acknowledged: number; critical_open: number }> => ({
      open: demoAlerts.filter((alert) => alert.state === 'open').length,
      acknowledged: demoAlerts.filter((alert) => alert.state === 'acknowledged').length,
      critical_open: demoAlerts.filter((alert) => alert.state === 'open' && alert.severity === 'critical').length,
    }),
    history: async (id: string): Promise<AlertHistoryResponse> => ({
      alert: demoAlerts.find((alert) => alert.id === id) || demoAlerts[0],
      history: [
        { id: 'h1', alert_id: id, from_status: 'open', to_status: 'open', note: 'Failure repeated', created_at: iso(0.2) },
        { id: 'h2', alert_id: id, to_status: 'open', note: 'Alert created', created_at: iso(2.2) },
      ],
      notifications: [
        { id: 'n1', alert_id: id, channel: 'email', recipient: 'admin@camwatch.com', message: 'Demo alert notification', status: 'logged', sent_at: iso(2.2) },
      ],
    }),
  },
  reports: {
    uptime: async (period: 'daily' | 'weekly' | 'monthly'): Promise<UptimeReport> => ({
      period,
      start_date: iso(24),
      end_date: iso(0),
      rows: demoDevices.map((device, index) => ({
        device_id: device.id,
        device_name: device.name,
        site_name: device.site_name || '',
        device_type: device.device_type,
        uptime_percent: [90.2, 100, 68.5, 96.4, 88.7][index] || 92,
        downtime_seconds: device.downtime_seconds,
        total_checks: 288,
        successful_checks: device.status === 'offline' ? 198 : 274,
      })),
    }),
    siteUptime: async (period: 'daily' | 'weekly' | 'monthly'): Promise<SiteUptimeReport> => ({
      period,
      start_date: iso(24),
      end_date: iso(0),
      rows: demoSites.map((site, index) => ({
        site_id: site.id,
        site_name: site.name,
        total_devices: site.total_devices || 0,
        camera_count: index + 1,
        nvr_count: 1,
        uptime_percent: [82.4, 100, 92.6][index],
        downtime_seconds: index * 3600,
        total_checks: 800,
        successful_checks: 730,
      })),
    }),
  },
}
